// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4udWSxvbN0HjfRV7-ayBCIKPEjEB9aXg',
    appId: '1:143593501299:web:6ff98d83e58d000d4bf006',
    messagingSenderId: '143593501299',
    projectId: 'learnvocabularyflutter',
    authDomain: 'learnvocabularyflutter.firebaseapp.com',
    storageBucket: 'learnvocabularyflutter.firebasestorage.app',
    measurementId: 'G-7YF79J8DHS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXREe_AmeQHoFRxGEwuucnSQImwRSx8-0',
    appId: '1:143593501299:android:6cef30e7e71195194bf006',
    messagingSenderId: '143593501299',
    projectId: 'learnvocabularyflutter',
    storageBucket: 'learnvocabularyflutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCzQCpE-IouGI-kWkQS5qOHSwyIFRsd2k',
    appId: '1:143593501299:ios:45b99fc3af11dc334bf006',
    messagingSenderId: '143593501299',
    projectId: 'learnvocabularyflutter',
    storageBucket: 'learnvocabularyflutter.firebasestorage.app',
    iosBundleId: 'com.example.learnvocabulary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCzQCpE-IouGI-kWkQS5qOHSwyIFRsd2k',
    appId: '1:143593501299:ios:45b99fc3af11dc334bf006',
    messagingSenderId: '143593501299',
    projectId: 'learnvocabularyflutter',
    storageBucket: 'learnvocabularyflutter.firebasestorage.app',
    iosBundleId: 'com.example.learnvocabulary',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4udWSxvbN0HjfRV7-ayBCIKPEjEB9aXg',
    appId: '1:143593501299:web:11e60037d73d2ad94bf006',
    messagingSenderId: '143593501299',
    projectId: 'learnvocabularyflutter',
    authDomain: 'learnvocabularyflutter.firebaseapp.com',
    storageBucket: 'learnvocabularyflutter.firebasestorage.app',
    measurementId: 'G-VTPR2CFCE7',
  );
}
